name: Actualizar lista unificada de IPs bloqueadas

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  update-lista:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Descargar listas públicas
        run: |
          mkdir -p listas
          curl -s https://www.spamhaus.org/drop/drop.txt -o listas/spamhaus_drop.txt
          curl -s https://www.spamhaus.org/drop/edrop.txt -o listas/spamhaus_edrop.txt
          curl -s https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt -o listas/emerging_block_ips.txt
          curl -s https://feodotracker.abuse.ch/downloads/ipblocklist.txt -o listas/feodo_blocklist.txt
          curl -s https://cinsscore.com/list/ci-badguys.txt -o listas/ci_badguys.txt

      - name: Combinar listas con la actual
        run: |
          echo "Generando lista unificada..."
          mkdir -p tmp
          cp lista.txt tmp/original.txt
          cat tmp/original.txt listas/*.txt > tmp/todas.txt
          grep -v '^#' tmp/todas.txt | grep -v '^\s*$' > tmp/filtradas.txt
          sort -u tmp/filtradas.txt > lista.txt
          echo "Tamaño final de lista:"
          wc -l lista.txt

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit y push si hay cambios
        run: |
          git add lista.txt
          git commit -m "Actualización diaria de lista unificada de IPs bloqueadas" || echo "Sin cambios"
          git push
